# Overrides for echo default configuration:
# https://github.com/spinnaker/echo/blob/master/echo-web/config/echo.yml

artifacts:
  gitrepo:
    enabled: true
    accounts:
    - name: git
      sshTrustUnknownHosts: true
